title: Food from A to Z
description: A website about food and typography. From fancy or fast food
  restaurants fonts to Tesco product lines and logo, this blog looks at
  different types of typography across multiple sectors of the food industry.
footer_text: Copyright 2021 Diana Miu
header_feature_image: ../uploads/ryan-concepcion-50kffxbjiog-unsplash.jpg
header_text: Food from A to Z
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
