title: Food from A to Z
description: A website about food and typography. From fancy or fast food
  restaurants fonts to Tesco product lines and logo, this blog looks at
  different types of typography across multiple sectors of the food industry.
footer_text: "Copyright 2021 Diana Miu "
header_feature_image: ../uploads/banner6.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/logo-draft2.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About Me
    siteurl: file:///C:/Users/diana/Desktop/aboutme/typographymodule/aboutme/draft2.html
